### ISSUE TITLE
The https://www.eclipse.org/documentation/ page missing entries for the 2023-09 and 2023-12 info centers

### ISSUE THREAD

**Issue by merks** [eclipse-simrel/help.eclipse.org#1]
The issue was raised here:

https://www.eclipse.org/lists/cross-project-issues-dev/msg19850.html

Of course the 2024-03 entry should be added when its available.

**Comment by jonahgraham** [comment]
xref: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4368

**Comment by nitind** [comment]
2023-09 **is** there.

**Comment by fredg02** [comment]
This issue has been fixed.
